```{r}
#install packages
library(sf)
library(here)
library(tidyverse)
library(dplyr)
library(stringr)
library(countrycode)
```
#Task 1
```{r}
#Read global gender inequality data
#read Composite Indices dataset
compDataset<-read_csv(here::here("HDR23-24_Composite_indices_complete_time_series.csv"))
#check if data is loaded
head(compDataset)
```

```{r}
#selecting columns containing data about global gender inequality
gi_index<-compDataset%>%
  dplyr::select(contains("iso3"), contains("country"), contains("gii"))

#see data
head(gi_index)
```

#Task2
```{r}
#read world spatial data 
worldSdataset<-st_read(here::here("World_Countries_(Generalized)_9029012925078512962.geojson"))

#seeing if data from dataset is loaded
head(worldSdataset)
```

```{r}
#clean gender inequality index dataset
gi_index<-gi_index%>% filter(!str_detect(iso3,"ZZ"))
             
#view the cleaned data
head(gi_index)
```

```{r}
#match column names in order to join
gi_index <- gi_index %>% rename(COUNTRY = country)

#joining csv file with geojson file
joined_data <-worldSdataset %>% left_join(gi_index, by = "COUNTRY")

head(joined_data)
```
#task 2

```{r}
#new dataset with column showing difference in inequality
joined_data <-joined_data %>% mutate(diff_2010_2019 = gii_2019 - gii_2010)

head(joined_data)

joined_data$diff_2010_2019
```

